	
	var underscore = require('underscore');
	underscore.mixin(require('underscore.string').exports());
	
	'use strict';
	
	// Hello Dude!
	
	// This is controller
	// When you browse localhost/kokotpica is _controller.js in /views-kokotpica run
	
	// To controller we send every request and response
	// Inside of REQ and RES is all response and request to the page
	
	// You can do everything on this page
	// You dont need NEVER edit different part of app
	// Create a million functions here and Result of your functions only sent as object to View
	
	// View is generated by res.render function
	// To View you can sent an object as second parameter
	// Object in screen can display with EJS
	// Check WTF is EJS on github.com/visionmedia/ejs
	// <%= versionSamko %>
	
	// If you need use any new require, only run 'npm install newModuleForAnApp' in root
	// Please, do not install kokotiny
	

	exports.Init = function(app, req, res) {
		
		//pull array of todos from json and send it as object

		var sample_todos = [
			{ 
				"content" : "asdf",
				"duedate" : "2013-01-09",
				"complete" : false
			},
			{ 
				"content" : "Buy some milk!",
				"duedate" : "2013-01-15",
				"complete" : false
			},
			{ 
				"content" : "Finish project documentation",
				"duedate" : "2013-01-01",
				"complete" : true
			},
			{ 
				"content" : "Hooray, weekend!",
				"duedate" : "2013-05-09",
				"complete" : false
			}
		];
		
		res.render(__dirname + '/_view.html', { 
			todos : sample_todos
		});

	};
	
	// function ConnectToDb(...) {...}
	// function MakeSuperObject(...) {...}
	// function FuckNiceSexyMilf(...) {...}