module.exports = function(req, res) {
	
	var object, user;
	
	// Generated by email
	user = getHash('a');
	
	// Get File From URL
	object = require('url').parse(req.url);
	object = object.pathname.substr(3);
		
	getObjectKey(user, object, function(key){
		console.log(key);
		getObjectContent(user, key, function(data){
			console.log(data);
		});
	});
	
};


var getHash = function(string) {
	
	string = require('crypto').createHash('sha512').update(string).digest('hex');
	return string.substr(10, 20);
	
};


var getObjectKey = function(user, objectHash, callback) {
		
	var s3,
	sdk = require('aws-sdk');

	sdk.config.update({ 
		accessKeyId : 'AKIAI5KY54XEDOMGQSCQ', 
		secretAccessKey : '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' 
	});
	s3 = new sdk.S3();

	s3.client.listObjects({
		Bucket : 'd41d8cd98f00',
		Prefix : user+'/markdown/'
	}, onData);
	
	function onData(err, data){		
		if (err) throw err;
		console.log(data);
		data.Contents.forEach(forEachFile);
	}
	
	function forEachFile(elem){		
		if (getHash(elem.Key)===objectHash) { 
			callback(elem.Key);
		}
	}
	
};


var getObjectContent = function(user, key, callback) {
	
	var s3,
	sdk = require('aws-sdk');

	sdk.config.update({ 
		accessKeyId : 'AKIAI5KY54XEDOMGQSCQ', 
		secretAccessKey : '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' 
	});
	s3 = new sdk.S3();
	
	s3.client.getObject({
		Bucket : 'd41d8cd98f00',
		Key : key
	}, function(err, data) {
		if (err) { throw err; }
		if (data) { callback(data); }
	});
	
};














